### ISSUE TITLE
Implement sorting filters

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#91]
The default is to sort alphabetically, but it should be possible for the user to sort his collection by date and to reverse that order
#### Requirements
- [x] Sorting interface
- [x] Sorting code. Pull the data from the cache, send it to the client and process it.
- [x] Fix https://github.com/interfasys/galleryplus/issues/56
#### Open questions
- Should we have a dropdown with 4 possibilities? 2 buttons? Where?
- Which date to use? Currently only the uploading date is available, but if meta data support is introduced then it would be possible to sort by date-the-picture-was-taken
- Should we we have more filters? Sort by brightness, colour, size, etc.

Designers: @jancborchardt 
Interested parties: @deMattin @Riechao @noooz @seuf @FredrikLindseth @Aesculapius @simonclausen

**Comment by deMattin** [comment]
For sorting I only see the filename, filedate and date picture is taken.
This could be a simple pulldown named "sorting" with this 6 options (every option and reverse).

The activated sorting should remain active as long as gallery is active and has to be reset to default if you restart gallery. I don't think, a user customizing of this "default" is neccessary.

With more meta data support it could be possible to **filter** the output.
I don't see the sorting in this context as a useful task.

But there are many questions remaining if you implement filters.
You have to get a list of existing (selected) meta-data in the current folder to set a filter only on existing values. How could such a "list" look like?

**Comment by jancborchardt** [comment]
At first we don’t really need an interface for it. Sorting should be by date taken by default. Alphabetic sorting makes 0 sense for photos.

After that, we can still judge if we really need other options.

**Comment by deMattin** [comment]
Alphabetic sorting does make sense!

Cameras save their picture names chronological in alphabetical order and if you have a collection of (renamed) photos it is normally also sorted alphabetically.
You can not really rely on the meta data "date taken" on cameras. They often have wrong dates because of previously empty batteries and not have setting correct date after such a "reset".

And if you rename, you have influence on sorting (thematic prefix).
Editing and correcting meta data is very often not done by many users.

So I definitly vote for alphabetical order as default as it is now!

**Comment by Koire** [comment]
@deMattin There are 2 problems I've found with this:
1.) The default of the gallery is to sort A-Z (smallest to largest -- reverse chronological order), and I have 4 or 5 years worth of photos from various smartphones, viewing my more recent photos is a hassle.
2.) Not every device uses the same naming convention. Some of my pictures are just the timestamp, some have img_date_time, some pic_datetime, some datetime, some yyyy-mm-dd-time -- it's bad because they become scattered and only sorted by the naming convention.

**Comment by oparoz** [comment]
And that's the reason I think we need some sort of panel with options so that people can configure the view the way they want to.

**Comment by jancborchardt** [comment]
And, well, sorting by date taken – newest first – should be the default.

@oparoz yeah, we could have that as a setting. However for every setting we really need to question if we actually need it.

**Comment by deMattin** [comment]
Sorting on filename (and reverse) are ready to use, fast and the reverse order function is easy to implement (#90).
Sorting on metadata (date taken or others) depend on looking in the file and certainly will be slower because you have to read ALL pictures first to sort them afterwards.

I think, to have the option, to sort the gallery folder as you need, is a fine feature and I support it.

But while generating the view and on first call (so it will be "default") I think it will be much slower with nothing appearing on the screen, if there will be a sort order with meta data as default.

Or do you want to wait until e.g. 500 picture previews are generated (picturesize and orientation matters for previews size and needed displayspace), metadata read of all files and after that all pictures are sorted and sent to browser?

If you have meta data as default, there also has to be a permanent "cache" and cache management for this data to be established because if not, you have to wait for this procedure to be finished every time you open a folder.

Again: Metadata sorting is a fine feature but only as a switching option if all pictures or previews are already generated AND displayed.
Gallery+ isn't very fast yet and it shouldn't slow down only because of a default view which will slow down all on design.

@Riechao: because of your "Point 1.)" I made #90 because this is also my problem and surely others will have it too.
Everybody, who is having a maintained picture folders won't need "date taken" at all because:
1. the picture names mostly content date/time or a serialized number
2. date taken corresponds to filename order if you have the same source
3. But they often need "reverse order" to show newest pictures first

Date taken is only needed, if you have different sources for your pictures in same folder and leave filenames as they are. I don't think, that's the usual case to reasonable slow gallery+ down.

Namesorting A-Z and Z-A could be the first step and metadata the second.
And if there is a solution, that doesn't slow down with metadata, we can discuss again, what should be default ... ;)

But I don't know how to get a progress in here:
Sorting by name and reverse are easy to implement but oparoz waits for a panel design.
I thing, if noone of the core designer team will have a look here, optional sorting will never come ... ;)

**Comment by oparoz** [comment]
A good point was made. Sorting by date taken can only work if we store the metadata in the database and would require some sort of data collection at upload time to be really usable.

**Comment by deMattin** [comment]
I hope, there was not only **one** good point .. ;)

But I really think, sorting should be made step by step:
1. filename and reverse sorting switchable
2. metadata sorting to be switchable in a already generated preview (no cache or db storage needed and we will see, how fast or slow this will be)
3. metadata sorting (picture taken) with permanent saved or cached meta data and its update management.
4. enhance metadata sorting from picture taken to whatever you can think of (metatags could even be customizable by user?)

I think, point 3. will be a really hard job because you have to be aware of meta data changing and there will be all problems, also the sync client has to deal with.
So I thing, it won't be a good idea to realize all in one step.

**Comment by jancborchardt** [comment]
Well – then we _should_ probably store that in the database. Proper apps like Dropbox can do it, and sort it by date – we should be able to as well. :)

**Comment by deMattin** [comment]
How many developers does dropbox have? :wink:

**Comment by jancborchardt** [comment]
I’m pretty sure comparing the number of developers doesn’t matter here. :) The point is that sorting is one of the main things in a pictures app, and something we should do right.

**Comment by deMattin** [comment]
It definitely does matter, how many developers there are!
Without oparoz the gallery+ won't exist and I see not much coding help here (sadly my skills are too low).

What you want to have is a big coding job and I think it won't be possible to realize this in more or less one step.
But noone other than oparoz will decide, how he acts further ...

**Comment by jancborchardt** [comment]
That’s why I would like to discuss it with @oparoz instead of talking about maybes. :)

**Comment by deMattin** [comment]
He is involved, surely listens and will tell us, what he thinks or will do next ... ;)
I don't think, this is a senseless blabla here. If we discuss this, it's possible to decide, what will be best approach to get all satisfied.
I see it as a sort of brainstorming.
Sadly as a non developer there's nothing more we or I can do (in addition to testing) to help the project ...

**Comment by oparoz** [comment]
From my pov, #90 is easy, as long as someone takes care of the UI. Same if we implement a simple sort by upload date, but for the rest, I think we're a long way off since the app doesn't currently store any data in the database.

So hopefully, the first steps can make 50+% of people happy and the rest will have to wait.

**Comment by oparoz** [comment]
if some of you need to have a default sorting order for some albums, you should test the `album-info` branch/PR
Information about the config file is in #93 .

**Comment by oparoz** [comment]
Can't be implemented until https://github.com/interfasys/galleryplus/issues/56 is fixed.

**Comment by oparoz** [comment]
Interesting parties can try the `sorting-buttons` branch.
I'm not going to spend any more time on the buttons, so designers will need to get involved to get this merged into master, but I will try to fix all reported sorting issues.

Note: Asset pipelining doesn't seem to be able to compile the scripts properly on my test setup. Let me know if this is also an issue for you.

**Comment by deMattin** [comment]
Sorting seems to work and I like the solution and the buttons.
But there is a problem with the svg-files.
They arise a second and then disappear:
![image](https://cloud.githubusercontent.com/assets/5565503/6886782/97cc0bda-d649-11e4-8562-db5a6fa5b103.png)
There seem two be 2 versions loaded - a correct one and a wrong one, witch overrides the right one:

> GET https://[domain]/apps/galleryplus/img/namedes.svg 404 (Not Found)
> 
> namedes.svg
> Dimensions 0 × 0
> File size 230B
> MIME type text/html
> URL https://[domain]/apps/galleryplus/img/namedes.svg

It seems to be the path.
The path is without "owncloud" but is webroot instead!
It is `https://[domain]/apps/galleryplus/img/namedes.svg` instead of `https://[domain]/owncloud/apps/galleryplus/img/namedes.svg`

Edit: And the inagename thing is fine, also - good work! :+1:

**Comment by oparoz** [comment]
I can't reproduce your icon issue. The paths are relative, so it's strange that it's adding them to the root folder, unless asset pipelining is enabled.

**Comment by deMattin** [comment]
No assets activated.
There have to be 2 places, where this icons are loaded in code.
They first arise and then disappear, as the breadcrump is displayed.
I also see in debugger the both loaded svg files.
The one with right path and the one with the wrong after that.

**Comment by oparoz** [comment]
Which browser? I've tried with Firefox, Chrome and BlackBerry 10 and they could all show the icons.
Do you see all 4 icons in your img folder?

**Comment by deMattin** [comment]
I've tried with my default "chrome" and with normally not used and cache cleared IE11, firefox and Nexus 4 (only for testing) .
All with 2 different owncloud accounts.
Again: The Icons are firstly shown but are overwritten by the "wrong path" ones!
So the first load does work but when broadcrum arises there is something, that goes wrong.
Maybe in the part, where the previews are generated and the actual sorting order is set.
I don't fully understand this part of code.

My first thought was a wrong mimetype of the "overwriting" error, because in the list of the loaded ressources, there is the correct one and the one with the "wrong path" and a false mimetype.

Icons are in img folder and not corrupt. But if this wouldn't be so, the short diplay of the icons won't work.

Edit: Also deactivated my theming and restarted apache - no success ... :/

**Comment by oparoz** [comment]
I've committed a change, but Github is misbehaving atm, so you'll have to wait to see if it helps.

**Comment by oparoz** [comment]
Github is under attack https://github.com/blog/1981-large-scale-ddos-attack-on-github-com

**Comment by deMattin** [comment]
Ok, I'll wait and meanwhile watch "Django unchained" ... :smile:

**Comment by oparoz** [comment]
Or replace line 452 in gallery.js with this:
`button.find('img').attr('src', '/apps/' + Gallery.appName + '/img/' + icon + '.svg');`
;)

**Comment by deMattin** [comment]
Sadly doesn't change anything ... :disappointed:

**Comment by oparoz** [comment]
Maybe it's a problem with the default sorting order. What did you set it at for that album?

**Comment by deMattin** [comment]
As I also tested in an account without any options set, this can't be the reason.

**Comment by oparoz** [comment]
Found the problem

**Comment by oparoz** [comment]
Should be fixed now

**Comment by deMattin** [comment]
Is fixed! Good work!
Tested on FF, Chrome and IE11.

**Comment by oparoz** [comment]
Thanks for testing :)

**Comment by oparoz** [comment]
I've asked IRC and Twitter for help...

For reference, this is what we have now. Too "graphical"
![3D buttons](https://oc8demo.interfacloud.com/index.php/s/zl40QgHbIfbntHw/download)

Those are the standard Font Awesome icons, but there isn't one for date sorting
![Standard buttons](https://oc8demo.interfacloud.com/index.php/s/GhqEzzckGPv4Alh/download)

**Comment by deMattin** [comment]
I found following issue:
If you switched sorting and then change folder, the button remains in switched state but sorting order is reset to default.

I think, best behaviour for the buttons and (manual) switching will be:
If you switch sorting, this sorting will be set on every folder you walk through during the gallery+ session - also ignoring all different settings in config file!
Manual settings in actual session should always overwrite presets, because you have a reason to do so.

**Comment by oparoz** [comment]
Thanks for the report. I think you're right. something was left behind...

I don't think we can override the config settings or it will be a pain to reset it for people who were just looking for something in one folder. 
One more reason to have a sorting panel, with lots of options. That way people can configure it the way they want.

**Comment by deMattin** [comment]
Ok, I see - you would have to save "clicked" event to decide, if the sorting has been manually set. Would be more complicated as I thought first ...

And thanks for the fix - resetting sort order now works as expected.

**Comment by deMattin** [comment]
I'm very interested in merging this into master.
So I created some ownCloud style icons for calendar sorting with fitting name icons:
![image](https://cloud.githubusercontent.com/assets/5565503/6977861/9e143dd4-d9c6-11e4-8e51-71bd4d44110d.png)

I would suggest to remove the 3D effect shadow and give the active icon simple a darker (and thicker) border.
The not active button should have the same border (1px) as other icons in ownCloud.
![image](https://cloud.githubusercontent.com/assets/5565503/6978273/7f14cc56-d9cf-11e4-844e-d3b24f321aa6.png)

Please have a look at my fork of gallery+:
https://github.com/deMattin/galleryplus
I have messed a bit with my branches and so merged all in master there.

Maybe the active border should be made thicker (2-3px).
I'll test this later.
Because everything in ownCloud is positioned with spacings and paddings and not alignment, it's really fun to change something ... ;)

One next step could be, to replace the "Teilen" text button with the share icon of ownCloud.

**Comment by deMattin** [comment]
Looks now like this:
![image](https://cloud.githubusercontent.com/assets/5565503/6981754/550653d4-da07-11e4-95ea-af34b35ddda6.png)
![image](https://cloud.githubusercontent.com/assets/5565503/6981774/ab1cdbd0-da07-11e4-8b5d-300c610390b5.png)

**Comment by oparoz** [comment]
There are several issues with the icons: alignment, font, size and the button is bigger as well, so in short, it's not clean.
I do think that this calendar works better though because it doesn't have the huge hinge at the top.
As for the border, I think the 3D effect still looks best.

**Comment by deMattin** [comment]
**Icon size**: No problem - can reduce size from actual 21px to 16px (though I liked it bigger and see no issue)
**Font**: it is a sans serif font like in "Teilen" and commplete ownCloud. What's wrong with that font?
**Button size**: as big as the other buttons (Teilen, Info) with 32px, What's wrong?
**3D button style**: I didn't like the previous 3D effect because the border is too small to really see this effect. So it's not really clear, which button is active or "pressed".
And second ownCloud has a flat style and 3D doesn't fit there.

Does it make sense to continue this fork or is it just waste of time?

**Comment by oparoz** [comment]
Size: The problems is that the padding needs to be the same or these buttons look more important, etc.
Font: The other items are in bold. A serif font would be better, to express that this works on text, etc.
Button size: It's wider
Styling: Having a flat design doesn't mean that you can't have shadows. Google's new material design raises buttons which are currently active per example. The main problem is that shadows slow things down, so I'm trying to avoid them. Inverting the colour of the button doesn't work as it's too in-your-face.

You can work on your fork, trying to find a solution and maybe we'll eventually find one, but I've spent a few hours on this already and concluded that professionals should get involved if we wanted to have something which can be merged.
My main problem is with the calendar icon. Once we find something which works, then it can probably be merged with the 3D effect or a lightness effect.

**Comment by oparoz** [comment]
I just want to add that I thought about using colours as well, but then it doesn't work for people who ~~pimp~~ theme their oC.

**Comment by deMattin** [comment]
Next try:

![image](https://cloud.githubusercontent.com/assets/5565503/6984705/ea890478-da2b-11e4-884a-ef4f58752c33.png)
![image](https://cloud.githubusercontent.com/assets/5565503/6984713/13eabe7e-da2c-11e4-9025-d0df908df2b7.png)
![image](https://cloud.githubusercontent.com/assets/5565503/6984724/3d066ef2-da2c-11e4-9f49-325d5f13f7cf.png)
![image](https://cloud.githubusercontent.com/assets/5565503/6984732/589482da-da2c-11e4-9387-33d0ce2439aa.png)

**Comment by deMattin** [comment]
I reworked the button borders and now it looks nice and is clean aligned (nothing jumping around) and all sizes, spacings and paddings are equal to other buttons.
And it doesn't depend on fontsize any more!
This way it looks very smooth and gentle but anyway you see the active selection.
What do you think?
![image](https://cloud.githubusercontent.com/assets/5565503/6988576/f7e96d02-da52-11e4-90c3-9f61bc018a54.png)
![image](https://cloud.githubusercontent.com/assets/5565503/6988608/452893b8-da53-11e4-9a56-c2ac33242086.png)
![image](https://cloud.githubusercontent.com/assets/5565503/6988614/606b2618-da53-11e4-9fb1-97ddd8e3f223.png)
![image](https://cloud.githubusercontent.com/assets/5565503/6988624/7cf5469c-da53-11e4-9583-f1b3e467be78.png)

## **Edit:**

Also the 3D `inset` flag is easy to set now without loosing alignment.
But as I mentioned before, I don't like it much, but it is ok...
![image](https://cloud.githubusercontent.com/assets/5565503/6988928/3cae04cc-da56-11e4-8afe-77560502782b.png)
And the not active sorting option should not get any styled border, I think.

**Comment by deMattin** [comment]
Now with share button:
![image](https://cloud.githubusercontent.com/assets/5565503/6989896/d2a9b65a-da61-11e4-960b-7663de7fd6ba.png)

![image](https://cloud.githubusercontent.com/assets/5565503/6989900/f1d16212-da61-11e4-9748-95a3068baff9.png)

All in `master` branch ...
https://github.com/deMattin/galleryplus

**Comment by oparoz** [comment]
Thanks. I don't know why the share button was never put in place, so I've just pushed a change to master to set it like the other ones.

Regarding the borders, I'm not sold on the thick border. I don't think it's used anywhere else either.
But that's not that important. It can be decided at the last minute.

You're going through the same route I took when testing icons and it's still not working. Spacing between elements is wrong and we can't see it's a calendar. It looks like a building when it's squeezed like that. I had the same problem with the icon I used.
It gave me an idea though and I'll try something these coming days, but I'm not sure it's going to work. These icons look too busy compared to the simplicity of the other ones.

**Comment by bill340** [comment]
Using the latest master, I still don't see any of the new buttons. Any suggestions?

**Comment by deMattin** [comment]
It's all in the master of my fork: https://github.com/deMattin/galleryplus
Feel free to pull it for a test or for usage (as I actially do).
The fork is current with main project page's master here enhanced with the above seen sorting buttons.
_Oparoz_ made a big commit tonight in his `master` (inheritance of comments) and I will update my fork's `master` today.
`Sorting-button` branch here on projekt page is a bit outdated and also not in sync with the `master` here.

**Edit:**
I will not update my `master` with the actual inheritance enhancement because _oparoz_ also changed the way, folder configuration is handled - too much manual work... ;)
So you can use or test my fork with a more actual base als the `sorting-buttons` branch here but it's not in sync with master here for now.

**Comment by deMattin** [comment]
@oparoz:
My last button version and code changes have correct spacings and sizes, I think.
What do you mean with _"Spacing between elements is wrong"_?

That we have no "thick border" or other marked as active button in ownCloud is caused by the fact, that we have no button showing active state at all in owncloud.
So it's neccessary to create something new here (and thicken the border isn't so bad).

It would be a good idea to implement _any_ version of sorting buttons in master. Why hide this feature and only give the users the chance, to test or use this only with an outdated test branch (or with my fork, also not fully in sync with main progress)?

I don't know, if you had a look at my code changes or pulled it for a test, but maybe you like the positioning of elements and borders if you switch buttons. This way you can modify and change borders with a simple way to realign elements in button.
And changing of icons or border style is a thing, that can be done with very few changes in code later, _if_ some real designer will have a better idea.
But on *"Font Awesome"" project the request for calendar sorting icons is made month (or years) ago and noone does it - so why shoud someone have an idea for a really great symbol **in 16x16 size** here?

**Comment by oparoz** [comment]
By spacing, I mean spacing between the arrow and the other element.
I didn't know that others were waiting for a new Font Awesome Icon... That really sucks.

The main reason it's not in master is because we're advised to not publish unfinished features and I want to release a new version of Gallery+, containing bug fixes and the new album feature. I also would like the design community to engage with the project because there are a few areas which need work.

**Comment by deMattin** [comment]
I fully understand, that you don't like to publish a feature that is not ready in your mind and fits all your needs. But it works perfect and it's only an issue on missing perfect design!
And the sorting button feature is so elementary, great and useable in everyday use!
It's ready to use and it only lacks (a bit) on design.

I don't know (or better to say, I disbelieve), if the "design community" will get active on something that is only in a more or less hiddden test branch.

Another problem is the fact, that it's hard to implement or try to enhance this in a fork, if it is so hard to merge master changes like it is actually.
I think, it's also for you more work now to implement sorting in master or to "rebase" sorting-buttons branch.

So a temporary solution could be to implement the feature in master but simply hide the sorting buttons with a simple css flag.
Or to implement the (in your mind) best looking version and so force the designers to get active ... ;)
What do you think?

**Comment by oparoz** [comment]
This gave me an idea... Adding a section in the configuration where people can enable features... That way unfinished design won't hurt the reputation of ownCloud while people who need a feature can use it at their own risk.

**Comment by deMattin** [comment]
Good idea!
With easily activatable "prerelease" features you can address more normal users (also for testing) that don't want to make use of github, branches and forks.

And branches are also more easily to maintain, because it's possible to merge working code earlier, where parts of the new features only miss some "fine tuning" but basically work.

**Different topic:**
I think, it would be better to remove css code changes out of js files like it is now for the button state visualisation.
Perhaps it could be possible to switch classes or ids or whatever in js code and have definitions of css only in css files.
Reason: As many others I themed my ownCloud install.
There I ran in an issue with this "css related things in js" on files app, where I have to theme and maintain a big js file on every update only because of one(!) variable, that could be better read out from css but is set in js file.

**Comment by oparoz** [comment]
You're right about css and JS, I'll see what I can do.

**Comment by deMattin** [comment]
@bill340:
Both branches (with sorting icons) are up-to-date now:

https://github.com/deMattin/galleryplus (branch: `sorting-update`)
![image](https://cloud.githubusercontent.com/assets/5565503/6999220/1cfcc0da-dc01-11e4-8e83-16f2f82c1103.png)

https://github.com/interfasys/galleryplus (branch: `sorting-buttons`)
![image](https://cloud.githubusercontent.com/assets/5565503/6999215/bc887410-dc00-11e4-8a0c-4c5e6c44e90e.png)

Same functionality but slightly different UI.

**Comment by jancborchardt** [comment]
Hey @oparoz – will you attend the ownCloud Contributor Conference in Berlin: https://owncloud.org/conf/?
Then we could talk and work on the Gallery interface. Also make it so we can use it as the proper ownCloud Pictures/Gallery app.

Cause it definitely needs some polish and atm I don’t really have time to indulge in these long discussions. And some of the changes like these odd 3D-style buttons and bunch of options for sorting veer a bit off the ownCloud style. :) So it would be great to touch base on that in person.

Or – where are you based? I could also just visit you for a few days and we could do some hackdays.

**Comment by jancborchardt** [comment]
@oparoz if you’re currently based in London then I’d definitely up for visiting – wanted to hang out with my GNOME homies there anyway. :D And if it’s Switzerland atm it’s also cool as I currently live in Munich.

**Comment by oparoz** [comment]
@jancborchardt - I think it would be both fun and useful to attend that conference :). I do agree that things get done faster when all participants can focus on the tasks at hand.
Hopefully, we can sort out the current problems quicker and use the conference to plan the interfaces for features which are yet to be developed, so that we don't get stuck when we want to actually implement them :)

As for a meet, Switzerland is best atm, I guess Zürich or Basel would be the best locations since my base is on the west side of Switzerland.

**Comment by jospoortvliet** [comment]
@oparoz but you should also submit a talk about the galleryplus app to the ownCloud conf to invite people to join the hacking frenzy on it ;-)

**Comment by oparoz** [comment]
@jospoortvliet - I'm thinking about it ;). Would be nice to have a plugin architecture by then to make it easier to add functionalities...

**Comment by oparoz** [comment]
Closing as the basics have been implemented. In order to be able to have more advanced filters, we need meta data support in core or in the app itself https://github.com/owncloud/gallery/issues/101.
